### ISSUE TITLE
India Todo list

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/india-forecast-app#2]
**Data Consumer**

Info: Collect National wind and PV data from https://sldc.rajasthan.gov.in/rrvpnl/rajasthan-overview

https://github.com/openclimatefix/ruvnl-consumer-app

- [x] script to pull this data
- [x] Create app that runs collects this data every x mins (probably every 30 mins with triggered by airflow). 
- [x] Would be nice if the app doesnt add any duplicate values in the database
Examples, GSPConsumer, PVConsumer, nwp-consumer, but these might be too complicated

**Forecast App**
- Make forecast app, which saves fake forecasts to database
  - [x] Create new repo, Have a look at [pv-site-production](https://github.com/openclimatefix/pv-site-production), [pvnet_app](https://github.com/openclimatefix/pvnet_app). Could copy/ adapt one, but I would tempted to make a new one which is really simple
  - [x] Should be an app, running with `click`. 
  - [x] Should have versioning, with bumpversion
  - [x] Should push a docker image
  - [x] Should run tests
  - [x] Can copy fake pv and wind algorithsm from fake API repo
  - [x] Should load a sites and run forecast for each one, and save to database
-  [ ] openclimatefix/india-forecast-app#11

Use [pvsite-Datamodel](https://github.com/openclimatefix/pv-site-datamodel)
- [x] add `asset_type` so site can be wind or solar - https://github.com/openclimatefix/pv-site-datamodel/issues/94
- [x] do something with `gsp` and/or `dno` (decided just to leave it for now)
- [ ] Change name of repo, maybe `quartz-site-datamodel` - https://github.com/openclimatefix/pv-site-datamodel/issues/93

**API**
- [x] openclimatefix/india-api#6
- [x] openclimatefix/india-api#7
- [x] openclimatefix/india-api#8

** Email **
- [ ] openclimatefix/india-api#16
- [ ] openclimatefix/india-api#15

**Infrastructure**
- [x] Deploy API 
- [x] Add RDS database 
- [x] Setup airflow
- [x] Run database migrations
- [x] openclimatefix/ocf-infrastructure#407
- [x] openclimatefix/ocf-infrastructure#408

**Comment by peterdudfield** [comment]
> I think we should also add a `country` field to the SiteSQL model in [pvsite-datamodel](https://github.com/openclimatefix/pv-site-datamodel) to make it easy to query the for India specific sites from the forecast app. Currently, there is `region` - but this is perhaps more specific than country-level.

yea lets do it, default to 'uk'
