### ISSUE TITLE
India site: Deploy models

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/india-forecast-app#78]
Deploy new site model that does site solar for new client

other tasks
- [x] openclimatefix/ocf-infrastructure -  https://github.com/openclimatefix/ocf-infrastructure/issues/603
- [x] openclimatefix/india-forecast-app - https://github.com/openclimatefix/ocf-infrastructure/issues/604
- [x] openclimatefix/india-forecast-app - https://github.com/openclimatefix/ocf-infrastructure/issues/605
- [x] Add a generic variable for use USE_SATELLITE for India like so https://github.com/openclimatefix/ocf-infrastructure/commit/f04eb29aab1492df318aef18cb8ca05b414921c0 (set to "true" for ad models, but default to "false" otherwise)

**Comment by peterdudfield** [comment]
This can be in this repo, after #79

**Comment by peterdudfield** [comment]
-[ ] Add module for Ad app like so https://github.com/openclimatefix/ocf-infrastructure/commit/c4eea72c433791774926a818b16cc585b825d314
- [ ] Add terraform variable for HF token and access it from AWS secrets manager
- [ ] Create a DAG for Ad model like so https://github.com/openclimatefix/ocf-infrastructure/commit/4d421e0d5480ebc45b046229788f276ecba818aa
- [ ] Add a generic variable for use USE_SATELLITE for India like so https://github.com/openclimatefix/ocf-infrastructure/commit/f04eb29aab1492df318aef18cb8ca05b414921c0 (set to "true" for ad models, but default to "false" otherwise)

**Comment by peterdudfield** [comment]
Currently deployed, but producing zeros

**Comment by peterdudfield** [comment]
Currently it doesnt look like the satellite values have been normalized

<img width="714" alt="Screenshot 2024-09-13 at 12 03 53" src="https://github.com/user-attachments/assets/aa17a23c-840d-40ea-b3ba-5cdc6021831b">

**Comment by peterdudfield** [comment]
Need to further look at NWP, slightly suprised by `sr`

<img width="704" alt="Screenshot 2024-09-13 at 12 05 20" src="https://github.com/user-attachments/assets/95108fbd-69aa-48c4-87cd-631893d38c98">

**Comment by peterdudfield** [comment]
For satellite data, it looks the values are between 0 and 335 in the zarr file. It looks ocf_datapipes normalizes with these values - https://github.com/openclimatefix/ocf_datapipes/blob/4bf534e999c6b28efb7889587adbfddc1d007cb0/ocf_datapipes/utils/consts.py. 
Need to check the training dataset

**Comment by Sukh-P** [comment]
Have deployed a baseline model to dev and prod now, some outstanding tasks still which can be listed on client-private
